project:
  type: website

website:
  title: "Joschka Flintz"
  search: false
  navbar:
    left:
      - text: "Research"
        href: research.qmd
      - text: "CV"
        href: assets/JFlintz_CV.pdf
        target: "_blank"
  page-footer: 
    right: "This website was created using [Quarto](https://quarto.org/){target='_blank'}."

format:
  html:
    #page-layout: full
    theme: cosmo
    css: styles.css
    toc: false
    fontsize: 14pt


