project:
  type: website

website:
  title: "Our Research"
  navbar:
    left:
      - projects.qmd
      - people.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

