project:
  type: website

website:
  title: "Joschka Flintz"
  search: false
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "CV"
        href: assets/JFlintz_CV.pdf
        target: "_blank"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    fontsize: 14pt


