---
title: "Research"
---

<div style="height: 15px;"></div>


## Journal Articles

<details>
  <summary>[**When Fans Travel: Determinants and Effects of Away Support in German Professional Football**](https://journals.sagepub.com/doi/10.1177/15270025261438384){target="_blank"}. Journal of Sports Economics (2026) | [GitHub](https://github.com/joschka-flintz/when-fans-travel){target="_blank"} </summary>
  <p style="font-size: 16px; margin-top: 10px; margin-left: 20px;">
This study examines the determinants of away fan attendance in Germany's top three football divisions over six seasons and assesses its impact on match outcomes. The analysis reveals that, after conditioning on home and away teams, distance and kick-off time are the most important predictors of away fan turnout. Moreover, away support is found to have a statistically significant positive effect on team performance: an additional 500 away fans are associated with a 2.3% to 3.8% increase in the probability of the away team winning the match. These findings suggest that league organizers should consider fan logistics and the potential influence of away fan presence when scheduling fixtures, in order to maintain sporting equity. At the club level, the results underscore the value of fostering fan engagement and indicate that strategies aimed at increasing away attendance may contribute to improved sporting outcomes.
  </p>
</details> 

<details>
  <summary style="margin-left: 20px;"><strong>Media Coverage</strong></summary>
  <div style="margin-left: 20px; margin-top: 10px;">

- [Studie zum Einfluss von Fußballfans bei Auswärtsspielen](https://www.ndr.de/fernsehen/sendungen/das_rote_sofa/studie-zum-einfluss-von-fussballfans-bei-auswaertsspielen,dasrotesofa-2426.html){target="_blank"}. *DAS! Rote Sofa, NDR* (2026)
- [Auswärtsfans und ihr Einfluss auf Fußballspiele](https://www.deutschlandfunknova.de/beitrag/fanfaktor-auswaertsfans-und-ihr-einfluss-auf-fussballspiele){target="_blank"}. *Deutschlandfunk Nova* (2026)
- [Auswärtsfans als Erfolgsfaktor im Fußball: Neue Studie zeigt klaren Zusammenhang](https://www.radioeins.de/programm/sendungen/die_profis/archivierte_sendungen/beitraege/wirtschaftsforschung--wie-fussballfans-den-ausgang-von-auswaerts.html){target="_blank"}. *Die Profis, radio eins, RBB* (2025)

  </div>
</details>


<div style="height: 15px;"></div>

<details>
  <summary>[**Emissionswirkungen der 2021 reformierten Kfz-Steuer: Eine empirische Analyse**](https://link.springer.com/article/10.1007/s11943-022-00310-w){target="_blank"} with Manuel Frondel and Marco Horvath. *AStA Wirtschafts-und Sozialstatistisches Archiv*  (2022)</summary>
  <p style="font-size: 16px; margin-top: 10px; margin-left: 20px;">
    At the beginning of 2021, the CO2-dependent component of the German vehicle tax was adjusted and made progressive, so that the tax burden for vehicles with high emission intensity increases disproportionately. This paper analyzes the effectiveness of the reformed vehicle tax in terms of its incentive effect and CO2 saving potential using the discrete demand model of Berry et al. (1995). Our estimation results show that with about 21,000 fewer cars sold annually as a result and a reduction in mean CO2 intensity of 0.74g/km, the annual CO2 emissions of newly purchased vehicles fall by about 60,000 tons. This moderate outcome is intuitive: an average tax increase of around 11 euros per annum does not have the steering effect that is needed to substantially reduce emissions. Our simulation results of a fictitious vehicle taxation with more progressive tax rates assumed here, which would result in an average tax increase of around 90 euros, would have significantly stronger effects and reduce the average CO2 emissions per kilometer of new cars by some 5g/km and reduce the number of new registrations by around 195,000 passenger cars. As a result, around 450,000 tons of CO2 might be saved annually. Nevertheless, a comparison with the annual emissions of the car fleet in Germany of around 100 million tons shows that even the effects of the fictitious progressive vehicle tax with higher tax rates would be very limited.
  </p>
</details>



## Working Papers

<details>
  <summary>[**The Value of Passenger Rail Access**](https://www.econstor.eu/handle/10419/306843){target="_blank"}. Ruhr Economic Papers (2024)</summary>
  <p style="font-size: 16px; margin-top: 10px; margin-left: 20px;">
This study quantifies the effect of train station openings on residential house prices across Germany over a 12-year period to provide generalizable evidence on the valuation of access to passenger rail by households. It is based on data on about 90 train station openings between 2009 and 2020 in Germany and a Difference-in-Differences model that uses three different control group variants to cover alternative assumptions about unobserved regional heterogeneity to mitigate problems arising from endogenous transport infrastructure provision. The results indicate that train station openings increase residential house prices on average by 5% (€18,000) within a distance of up to two to three kilometers. Notably, these positive effects are observed exclusively for properties without prior access to passenger rail services, and are significantly larger in more densely populated and urban areas.
  </p>
</details>

<div style="height: 15px;"></div>

<details>
  <summary>[**Individual Mobility and Public Transport Subsidies**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5087739){target="_blank"} with Mark Andor and Colin Vance. USAEE Working Paper (2025)</summary>
  <p style="font-size: 16px; margin-top: 10px; margin-left: 20px;">
Politicians around the world are looking for ways to reduce the negative externalities of the transport sector. Subsidization of public transport is a popular remedy, but evidence on the associated causal effects remains scant. Based on a randomized controlled trial that tracks mobility behavior continuously via a mobile app, this study provides causal evidence on how individuals modify their mobility patterns when provided with temporary cost-free access to public transport. We further explore whether such access induces enduring shifts in mobility behavior after the reinstatement of regular fares. We randomly provide roughly half of our around 420 participants - whose selection targeted car users - with a one-month public transport ticket for their local area, and monitor travel behavior across all modes over three months. We find a statistically significant average increase of about two trips per month using public transport during the subsidization period. The rise in public transport utilization, however, is not paralleled by a reduction in car usage, nor does it yield a persistent alteration in mobility behavior in the subsequent month after the ticket expires.
  </p>
</details> 

<div style="height: 15px;"></div>

<details>
  <summary>[**Train Stations and Car Registrations: Evidence from Station Openings in Germany**](https://www.ifo.de/en/cesifo/publications/2026/working-paper/train-stations-and-car-registrations-evidence-station-openings){target="_blank"} with Stefanie Gäbler, Viktoria Kleinschmidt and Felix Rösel. CESifo Working Paper (2026)</summary>
  <p style="font-size: 16px; margin-top: 10px; margin-left: 20px;">
  Does better railway infrastructure encourage people to register less private cars? We analyse the opening of 170 train stations in Germany between 2010 and 2022 and compare them to a control group of locations that were identified as potential sites for new stations. Using a difference-in-differences approach, we find that annual car registrations within the catchment area of a newly opened station decline by at least 3.5 to 5.5 percent permanently. These effects are consistent in both urban and rural settings and correspond, on average, to at least 140 fewer car registrations over ten years for each new station. Further evidence suggests that the effects are driven by habit changes rather than by spatial sorting, leading to the conclusion that new train stations reduce the number of car registrations both locally and globally. 
  </p>
</details>

## Work in Progress


<details>
  <summary>**Labor market tightness and business successions** with Jan Cornelius Peters and Martin Simmler.</summary>
  <p style="font-size: 16px; margin-top: 10px; margin-left: 20px;">
  This paper studies the causal impact of skilled labor shortage on business successions, particularly on  their failure   resulting in firm exits. We outline an illustrative search model of managerial succession and empirically assess its     implications using firm level trade registry information from 2013 to 2023 combined with survey data on labor market     tightness at the level of region-sector cells. Identification exploits the increasing propensity to resign as            owner-managers approach retirement age. The results indicate that tighter labor markets significantly raise the likelihood of firm exit among firms led by older managers. Specifically, a one-standard-deviation increase in labor market tightness increases the probability of firm exit by 2.1 percentage points for firms with managers older than 50 years. Conditional on manager resignation, this corresponds to an increase in firms' exit probability of approximately 13 percentage points.
  </p>
</details>


<!-- ::: -->

<!-- ::: -->




